theme: jekyll-theme-minimal
title: Yuhao's homepage
description: I will post some notes of studying economics here.
head:
  - "<script type=\"text/javascript\" async
      src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML\"></script>"
